#!/usr/bin/env node
/**
 * Naive-agent benchmark: deterministically simulates the retry loop an
 * unprotected agent falls into, and measures what it costs.
 *
 * Usage:  node dist/bench.js [--scenario <name>] [--max-attempts N] [--out file.jsonl]
 *
 * Model (documented assumptions, all deterministic):
 *  - The "agent" retries the failing tool immediately until success or max attempts
 *    (that is the observed pathological behavior this project exists to stop).
 *  - Every retry is a fresh model turn: the ENTIRE conversation so far — including
 *    every previous error payload — is re-sent as input tokens.
 *  - BASE_CONTEXT_TOKENS approximates system prompt + task + tool definitions.
 *  - REASONING_TOKENS_PER_TURN approximates the agent's "let me try again" output.
 *  - Tokens are counted with gpt-tokenizer (BPE) over the exact bytes the agent
 *    would see — an approximation of Claude's tokenizer, labeled as such.
 */
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { classify } from "mcp-fuse-core";
import { encode } from "gpt-tokenizer";
import { appendFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SCENARIO_NAMES } from "./scenarios.js";

const BASE_CONTEXT_TOKENS = 2000;
const REASONING_TOKENS_PER_TURN = 60;
const CALL_TIMEOUT_MS = 15_000;

function arg(name: string, fallback?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const scenarioName = arg("scenario", "rate-limit-storm")!;
const maxAttempts = Number(arg("max-attempts", "8"));
const outFile = arg("out");
/** --wrapped routes the same scenario through the real mcp-fuse proxy. */
const wrapped = process.argv.includes("--wrapped");

if (!SCENARIO_NAMES.includes(scenarioName)) {
  console.error(`unknown scenario "${scenarioName}" — expected one of: ${SCENARIO_NAMES.join(", ")}`);
  process.exit(2);
}

const serverJs = path.join(path.dirname(fileURLToPath(import.meta.url)), "server.js");
const tokens = (text: string): number => encode(text).length;

interface Attempt {
  attempt: number;
  outcome: "success" | "error" | "transport-error";
  resultTokens: number;
  inputTokens: number;
  wallMs: number;
  text: string;
}

let serverArgs = [serverJs, scenarioName];
if (wrapped) {
  const require = createRequire(import.meta.url);
  const proxyCli = path.join(path.dirname(require.resolve("mcp-fuse")), "cli.js");
  serverArgs = [proxyCli, "wrap", "--", process.execPath, serverJs, scenarioName];
}
const transport = new StdioClientTransport({
  command: process.execPath,
  args: serverArgs,
  stderr: "inherit",
});
const client = new Client({ name: "flaky-bench", version: "0.0.1" });
await client.connect(transport);

const attempts: Attempt[] = [];
let conversationTokens = 0;

for (let attempt = 1; attempt <= maxAttempts; attempt++) {
  const inputTokens = BASE_CONTEXT_TOKENS + conversationTokens;
  const t0 = Date.now();
  let outcome: Attempt["outcome"];
  let text: string;
  try {
    const res = (await client.callTool(
      { name: "get_user_data", arguments: { userId: "42" } },
      undefined,
      { timeout: CALL_TIMEOUT_MS },
    )) as { isError?: boolean; content?: Array<{ type: string; text?: string }> };
    text = (res.content ?? [])
      .filter((c) => c.type === "text" && typeof c.text === "string")
      .map((c) => c.text)
      .join("\n");
    outcome = res.isError ? "error" : "success";
  } catch (e) {
    outcome = "transport-error";
    text = String(e);
  }
  const resultTokens = tokens(text);
  conversationTokens += resultTokens + REASONING_TOKENS_PER_TURN;
  attempts.push({ attempt, outcome, resultTokens, inputTokens, wallMs: Date.now() - t0, text });
  if (outcome === "success") break;
}

await client.close();

const errors = attempts.filter((a) => a.outcome !== "success");
const errorTokens = errors.reduce((sum, a) => sum + a.resultTokens, 0);
const cumulativeInputTokens = attempts.reduce((sum, a) => sum + a.inputTokens, 0);
const succeeded = attempts.at(-1)?.outcome === "success";

// Projection: behind mcp-fuse the agent sees at most ONE guidance message,
// generated by the actual mcp-fuse-core classifier from the first raw error.
const firstError = errors[0];
const guidance = firstError
  ? classify({ message: firstError.text }).agentGuidance ?? ""
  : "";
const guidanceTokens = tokens(guidance);
const savedTokens = Math.max(0, errorTokens - guidanceTokens);
const savedPct = errorTokens > 0 ? ((savedTokens / errorTokens) * 100).toFixed(1) : "0";

const pad = (v: string | number, w: number) => String(v).padStart(w);
console.log(
  `\nScenario: ${scenarioName}  (naive agent, max ${maxAttempts} attempts${wrapped ? ", WRAPPED in mcp-fuse" : ", unprotected"})\n`,
);
console.log(" attempt | outcome          | tool-result tokens | input tokens (context replay) | wall ms");
console.log("---------|------------------|--------------------|-------------------------------|--------");
for (const a of attempts) {
  console.log(
    ` ${pad(a.attempt, 7)} | ${a.outcome.padEnd(16)} | ${pad(a.resultTokens, 18)} | ${pad(a.inputTokens, 29)} | ${pad(a.wallMs, 6)}`,
  );
}
console.log(`
${wrapped ? "Agent behind mcp-fuse" : "Unprotected agent"}: ${attempts.length} tool call(s), ${errors.length} error payload(s)${succeeded ? "" : ", NEVER RECOVERED"}
  error tokens entering context:   ${errorTokens}
  cumulative input tokens (retry turns replay full context): ${cumulativeInputTokens}
`);
if (wrapped) {
  console.log(
    "MEASURED behind the real proxy — error rows above are compact fuse guidance messages, not raw payloads. Compare with the same scenario run without --wrapped.",
  );
} else if (firstError) {
  console.log(`With mcp-fuse (projected): 1 guidance message = ${guidanceTokens} tokens`);
  console.log(`  "${guidance}"`);
  console.log(`  → ~${savedTokens} error tokens (${savedPct}%) kept out of context, retries handled below the protocol\n`);
}
console.log("(token counts: gpt-tokenizer BPE over exact agent-visible bytes — an approximation of Claude tokenization)");

if (outFile) {
  const record = {
    scenario: scenarioName,
    maxAttempts,
    attempts: attempts.map(({ text: _text, ...rest }) => rest),
    succeeded,
    errorTokens,
    cumulativeInputTokens,
    projected: { guidanceTokens, savedTokens },
  };
  appendFileSync(outFile, JSON.stringify(record) + "\n");
  console.log(`\nwrote ${outFile}`);
}
